version: 0.0
os: linux
files:
  - source: /
	destination: /home/ubuntu/pronounce-api
hooks:
	ApplicationStop:
		- location: scripts/stop.sh
			runas: root
	AfterInstall:
		- location: scripts/start.sh
			runas: root